### ISSUE TITLE
Validate Date and Fy.year

### ISSUE THREAD

**Issue by MatthewKatzen** [HughParsonage/grattan#130]
Create function for each of the parameters which:
1. Checks validity
2. Returns messages/errors
3. Sets defaults

**Comment by HughParsonage** [comment]
Good idea. I've done something for the financial years:

https://github.com/HughParsonage/grattan/blob/master/R/verify_fys_permitted.R

though this doesn't feature *3. sets defaults*. A slight problem I've found is tuning for performance as well as emitting a good error message, but I think these are possible to overcome with a flexible enough validation function.

**Comment by MatthewKatzen** [comment]
Decided to omit _3. sets default_ as it will probably be too function specific.

**Comment by HughParsonage** [comment]
Financial years are particularly onerous. A possible solution is to add attributes with the following information:

* are all the values valid financial years?
* what is the range of financial years?

**Comment by HughParsonage** [comment]
Closed by #133
