### ISSUE TITLE
Model capital gains tax (discount) in `model_income_tax`

### ISSUE THREAD

**Issue by HughParsonage** [HughParsonage/grattan#134]
Matt, something slightly off-topic but could make the `model_rent_assistance` part a bit easier to understand.

Modify `model_income_tax.R` so that we can model a change to the capital gains tax discount rate. Some things to know:

* If you receive a capital gain more than a year after purchase, currently only 50% of that is taxable. This is known as the capital gains tax discount. We'd like to be able to see the distributional effect of changing this rate.
* `Net_CG_amt` is the column in the sample files containing the amount of capital gains each taxpayer earned in that tax year, after the 50% discount (if applicable).
* You should have a parameter that represents the change in capital prices for a particular change in the tax discount rate. (It's okay to just make this a fixed amount, e.g. just a single number).

**Comment by MatthewKatzen** [comment]
Does the `Tot_CY_CG_amt` column contain the original capital gain before the discount?

**Comment by HughParsonage** [comment]
Kind of...

The total capital gain is the “true” capital gain and the net is the
“taxable” gain. The main difference is the discount but not the only one

**Comment by MatthewKatzen** [comment]
Should it be assumed that if someone's `Net_CG_amt` is the same as their `Tot_CY_CG_amt` that they are ineligible for the discount?
