### ISSUE TITLE
Projections of superannuation variables

### ISSUE THREAD

**Issue by HughParsonage** [HughParsonage/grattan#14]
The `project` function needs to create suitable forecasts for the `MCS` variables.

**Comment by HughParsonage** [comment]
OK this was already done.. 

### Current assumptions

- `MCS_Emplr_Contr`, `MCS_Prsnl_Contr`, and `MCS_Othr_Contr` grow by (the projected) wage inflator

- `MCS_Ttl_Acnt_Bal` grows by a **hard-coded** value of 5% p.a.

Important to note that this is a static model -- in particular each row in the sample file does not age. So the total balance projections do not reflect fund growth or additional contributions.

**Comment by youncg81** [comment]
That looks good.  The balance growth is reasonable for projections, basically wages plus a maturity factor so defensible.  However, it is better to account for earnings when they are known, but the index is tricky in a static model.  If you don't, balances will fall behind on your total asset benchmark - and you could look at this in your data.  I.e. the period where we have had good returns recently (~10% give or take), growth aggregate assets at 5% + pop wont keep up.

Wages are uprated by AWE, or total wages/total earners.  So the equivalent for this is total super assets (maybe just accum phase?)/total persons.  

Super balances are a touch trickier as balances grow by earnings (related to returns) plus contributions (related to earnings), so average balance grows at somewhere between the two, weighted more by the return the higher your balance relative to your contributions.  

〖Bal〗_(t+1)^31= 〖Bal〗_t^30+〖Cont〗_t^30+〖Earns〗_t^30=(1+r)×〖Bal〗_t^30+〖Cont〗_t^30

Easiest solution, probably just average change in super assets per person.



When uprating contributions for future years, do the other component parts also grow by wages? Including:
- Non_emp_spr_amt
- Rptbl_Empr_spr_cont_amt

Sorry if there is already a place you do this, but I would calculate the contribution variables of interest at some point (before or after uprating wouldnt matter):
sg = max ( MCS_Emplr_Contr - Rptbl_Empr_spr_cont_amt )
salSac = Rptbl_Empr_spr_cont_amt 
persDeduct = Non_emp_spr_amt
preTax = sg + sal + persDeduct
postTax = max ( MCS_Prsnl_Contr - persDeduct  )

**Comment by youncg81** [comment]
Sorry, forgot to say: hitting your benchmark is key.  Due to sampling bias in the tax file, total assets wont hit between APRA and the sample file, but I would think they should roughly track one another
