### ISSUE TITLE
Rent assistance decreases as fy.year increase

### ISSUE THREAD

**Issue by MatthewKatzen** [HughParsonage/grattan#146]
`rent_assistance(fortnightly_rent = 200, fy.year = "2015-16")` = `63.6975`
`rent_assistance(fortnightly_rent = 200, fy.year = "2016-17")` = `62.5125`
RA should be increasing with fy.year.

But note that `rent_assistance(fy.year = "2015-16")` = `129.47`
`rent_assistance(fy.year = "2016-17")` = `131.05` which is correct. 
Therefore the error must be with the rent amount

**Comment by HughParsonage** [comment]
But the minimum rent thresholds also increase.
