### ISSUE TITLE
Update medicare and sapto tables 

### ISSUE THREAD

**Issue by HughParsonage** [HughParsonage/grattan#17]
> The Government will increase the Medicare levy low-income thresholds for singles,
> families and seniors and pensioners from the 2015-16 income year. The increases take
> account of movements in the Consumer Price Index so that low income taxpayers
> generally continue to be exempted from paying the Medicare levy.
> 
> The threshold for singles will be increased to $21,335. For couples with no children, the
> threshold will be increased to $36,001 and the additional amount of threshold for each
> dependent child or student will be increased to $3,306. For single seniors and
> pensioners, the threshold will be increased to $33,738. For senior and pensioner
> couples with no children, the threshold will be increased to $46,966 and the additional
> amount of threshold for each dependent child or student will be increased to $3,306. 

See Budget Paper number 2. Pdf page = 39.

http://www.budget.gov.au/2016-17/content/bp2/download/bp2_consolidated.pdf

**Comment by HughParsonage** [comment]
@youncg81 Are you able to verify that the tables was already updated?

e.g. run `income_tax(`*some number*`, fy.year = "2016-17", age = 45` and `age = 66)` and verify numbers are correct.

**Comment by youncg81** [comment]
@HughParsonage  Yup, I'm getting the same results in a separate spreadsheet.
