### ISSUE TITLE
turn Budget2019_lamington on by default for relevant financial years

### ISSUE THREAD

**Issue by MattCowgill** [HughParsonage/grattan#188]
When running `model_income_tax()` on a financial year in which the LMITO is in effect, the Budget2019_lamington argument should be TRUE by default

**Comment by MattCowgill** [comment]
I’ll do this after the legislation has passed

**Comment by MattCowgill** [comment]
planning to do this over summer

**Comment by MattCowgill** [comment]
I note that this is effectively done in https://github.com/HughParsonage/grattan/commit/931c248147cc403e1a4610ce32da25dab3df0f79, though the documentation still says it is `FALSE` by default. `Budget2019_lamington` is now `NA` by default; when it is NA, the lamington is automatically calculated and included for the relevant financial years (2018-2021). `Budget2018_lamington` remains `FALSE` by default.

**Comment by HughParsonage** [comment]
Ta. For the record, I think my approach of adding argument to `model_income_tax` is the wrong one and in the future it would be best to just copy the function into one for each budget. Pretty impossible to maintain backwards compatibility over multiple Budget Speeches, even when the announcements are minor.
