### ISSUE TITLE
Separate medicare levy

### ISSUE THREAD

**Issue by HughParsonage** [HughParsonage/grattan#20]
- [x] Separate `medicare_levy` from its current location within `grattan:::rolling_income_tax()`. 
- [ ] Provide new function `new_medicare_levy` returning the medicare levy payable for an arbitrary policy.

**Comment by HughParsonage** [comment]
@youncg81: this should be what you were after. A new function, `new_medicare_levy` returns a new *function* (not object), when a `parameter_table` is supplied. The documentation will probably need to be improved, but I think the core is there. 

Also fixed up Medicare Levy back to 2003-04, including family income, children, and SAPTO parameters.

Compare the changes here: https://github.com/HughParsonage/grattan/compare/90cadee40e0edb35a346adf52ed2cffe760f5c38...bdffb341f33a0121b77254d91f51e31c4e8ec202

Tests provided.

**Comment by youncg81** [comment]
Thanks Hugh

**Comment by youncg81** [comment]
Although I'm going to have to get you to show me how to use this thing
