### ISSUE TITLE
cpi_inflator_general_date returning NAs

### ISSUE THREAD

**Issue by MattCowgill** [HughParsonage/grattan#211]
It's unclear to me whether there is something wrong with the function, or if I have misunderstood the intended use (there are no examples in the documentation). 

``` r

library(grattan)

cpi_inflator_general_date(from_nominal_price = 1, 
                          from_date = as.Date("2010-01-01"), 
                          to_date = as.Date("2020-01-01"))
#> [1] NA

cpi_inflator_general_date(from_nominal_price = 1, 
                          from_date = as.Date("2010-01-01"), 
                          to_date = as.Date("2020-01-01"),
                          adjustment = "none")
#> [1] NA
```

<sup>Created on 2020-05-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by MattCowgill** [comment]
what was the problem here, @HughParsonage ?

**Comment by HughParsonage** [comment]
When the date extended beyond the internal data, it just reported a missing value. It now pursues a forecast.
