### ISSUE TITLE
print_2heading_xtable nukes caption etc.

### ISSUE THREAD

**Issue by soodoku** [HughParsonage/grattan#32]
I pass a couple of things to xtable --- stuff like caption and label (which I plan to use for referencing table) but both are nuked when I pass through print_2heading_xtable 

I believe the problem is line 115:
https://github.com/HughParsonage/grattan/blob/master/R/print_2heading_xtable.R

You only allow it to pass align. I would rec. support all the arguments, no?

One option is to allow caption and label as args in the print_2heading_xtable function.

Another is to separate out print from xtable generation.

That will allow you to support ... (that is allow user to pass all allowed arguments) for xtable and print separately as they are two separate functions

**Comment by HughParsonage** [comment]
Agreed. I've opened a PR to allow `xtable::xtable` arguments to be passed via the function. Thanks! Let me know if this is satisfactory.
