### ISSUE TITLE
calling functions from external libs

### ISSUE THREAD

**Issue by soodoku** [HughParsonage/grattan#33]
In print_2heading_xtable.R and elsewhere, it seems the calls to functions from external libs are made using double colons, e.g. dplyr::lead

A simpler way to call functions is to issue import for specific functions like so:
https://github.com/soodoku/abbyyR/blob/master/R/abbyyR.R

And then just call them without the double colons from any of the functions in the pkg.

**Comment by HughParsonage** [comment]
Personal style. I like to know the namespace for functions I irregularly call.
